site_name: Kupia Audit Arsenal
site_description: A comprehensive knowledge hub for Web3 security auditors
site_author: KupiaSec

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: docs/overrides
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

docs_dir: docs

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

nav:
  - Home: index.md
  - Audit:
    - Overview: audit/index.md
  - DeFi Concepts:
    - Overview: defi/index.md
  - Podcast Insights:
    - Overview: pod

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KupiaSec
    - icon: fontawesome/brands/twitter
      link: https://x.com/KupiaSecurity

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
copyright: "All content belongs to respective video owners. This site is for educational purposes only."